name: "Check Python"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64' 
    - run: pip install numpy
    - run: pip install sklearn
    - run: python src/main.py
