name: A workflow for my Hello World file
on: push
jobs:
  install-runner:
    runs-on: ubuntu-20.04
    name: Install runner
    steps:
      - name: Authenticate
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
          OPENSHIFT_NAMESPACE: default
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: default
      - name: Install self hosted runner into this repository
        uses: redhat-actions/openshift-actions-runner-installer@v1
        with:
          github_pat: ${{ secrets.PAT }}
      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          oc: "3"
          helm: "latest"

  self-hosted-workflow :
    name: Running on OpenShift runner
    runs-on: [self-hosted]
    steps:      
      - uses: actions/checkout@v2
      - name: Scan valid yaml with kube-linter
        uses: stackrox/kube-linter-action@v1.0.2
        with:
          directory: sample/valid-yaml
