name: "Check Python Then Trigger Hello World"

on: 
  push:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64' 
      - run: pip install numpy
      - run: pip install sklearn
      - run: python src/main.py
      - name: Call Hello World Action - Dispatch initiating repository event
        if: github.event.action != 'return'
        run: |
          curl -X POST https://api.github.com/repos/dev0701/hello-github-actions/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -u ${{ secrets.WORKFLOW_SECRET}} \
          --data '{"event_type": "ping", "client_payload": {"repository": "'"$GITHUB_REPOSITORY"'" }}'
      - name: Acknowledge Hello World Action
        if: github.event.action == 'return'
        run: |
          echo "Hello World ran from '${{ github.event.client_payload.repository }}'" && \
          curl -X POST https://api.github.com/repos/dev0701/hello-github-actions/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -u ${{secrets.WORKFLOW_SECRET}} \
          --data '{"event_type": "acknowledge", "client_payload" : { "repository": "'"$GITHUB_REPOSITORY"'" }}'

    
